### ISSUE TITLE
Create first Figma page for the list of tags

### ISSUE THREAD

**Issue by Daniel-Stoica** [remote-labs-sarl/hire-frontend#3]
Migrate the existing mockup of the tags page to Figma.

**Comment by webmaster019** [comment]
I've already finished can you do a review?

**Comment by danlex** [comment]
<img width="463" alt="Screenshot 2023-01-20 at 12 23 16" src="https://user-images.githubusercontent.com/1996653/213691478-6d947b18-d46a-45bb-a8d3-501948dba7d5.png">

**Comment by danlex** [comment]
For the search maybe we can have an autocomplete with predefined tokens, first we can have there the technologies.

**Comment by webmaster019** [comment]
Yes that's what I'm planning
