### ISSUE TITLE
Hire > architecture > Overview diagram

### ISSUE THREAD

**Issue by danlex** [remote-labs-sarl/hire-frontend#5]
Create a diagram with the main components of the Hire application based on the User journey.
It should be clear what components are involved and how they interact.

<img width="1732" alt="Screenshot 2023-01-20 at 13 16 38" src="https://user-images.githubusercontent.com/1996653/213693202-a4e0b960-74d1-4224-b4bf-b3c6575b04b3.png">

**Comment by JohnDoeee123** [comment]
Done. Created another task for FE overview diagram
